name: Publish Extension

on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  cache: "npm"

            - name: Install Dependencies
              run: npm ci

            - name: Compile Extension
              run: npm run build

            - name: Install VSCE (VS Code Extension Manager)
              run: npm install -g @vscode/vsce

            - name: Publish to VS Code Marketplace
              run: vsce publish
              env:
                  # You must generate a Personal Access Token in Azure DevOps
                  # and save it in your GitHub Repository Secrets as VSCE_PAT
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
